### ISSUE TITLE
feat: negative testing in VerifyReachability

### ISSUE THREAD

**Issue by andrewbonney** [aristanetworks/anta#1047]
It would be useful to be able to test that certain networks are **not** accessible from others using VerifyReachability. Could an attribute be added to select whether the test is expected to return a success status or a failure status, which defaults to the current success state?

**Comment by carl-baillargeon** [comment]
Hi @andrewbonney 

I guess we could add an optional field like `expected_unreachable: bool = False` to the input model to accomplish this. Example:
```yaml
    anta.tests.connectivity:
      - VerifyReachability:
          hosts:
            - source: Management0
              destination: 1.1.1.1
              vrf: MGMT
              expected_unreachable: true
```
Would that work?
