### ISSUE TITLE
feat(anta.tests): Input factories should support multiple inputs.

### ISSUE THREAD

**Issue by vitthalmagadum** [aristanetworks/anta#1069]
Currently, some tests have the format 
```
anta.tests.routing:
      generic:
        - VerifyRoutingTableEntry:
            vrf: default
            routes:
              - 10.1.0.1
              - 10.1.0.2
```
The expected format should be
```
anta.tests.routing:
      generic:
        - VerifyRoutingTableEntry:
            - vrf: default
              routes:
                 - 10.1.0.1
                 - 10.1.0.2
            - vrf: <name>
              routes:
                 - x.x.x.x
                 - y.y.y.y
```
