### ISSUE TITLE
Enhancement(anta.tests): Hardware module tests should impose input restrictions on fields using field validators

### ISSUE THREAD

**Issue by vitthalmagadum** [aristanetworks/anta#1070]
Currently, some tests are accepting inputs as plain strings. We should implement field validation in these cases.

Example:
```
anta.tests.hardware:
      - VerifyEnvironmentPower:
          states:
            - ok
```

We have possible values for Fan status for example
`'failed', 'ok', 'unknownHwStatus' `
