### ISSUE TITLE
Enhancement(anta.tests): Generate examples/tests.yaml to Include Multiple Examples in Docstrings

### ISSUE THREAD

**Issue by vitthalmagadum** [aristanetworks/anta#1097]
We have scenario

```
class Input(AntaTest.Input):
"""Input model for the VerifyNTPAssociations test."""

  ntp_servers: list[NTPServer] | None = None
  """List of NTP servers."""
  ntp_pool: NTPPool | None = None
  """NTP servers pool."""
```

For this;

```
Examples
--------
```yaml
anta.tests.system:
  - VerifyNTPAssociations:
      ntp_servers:
        - server_address: 1.1.1.1
          preferred: True
          stratum: 1
        - server_address: 2.2.2.2
          stratum: 2
        - server_address: 3.3.3.3
          stratum: 2
  - VerifyNTPAssociations:
      ntp_pool:
        server_addresses: [1.1.1.1, 2.2.2.2]
        preferred_stratum_range: [1,3]
    ```
```

The current implementation of the script does not support the inclusion of multiple examples within the examples. The script should properly parse and handle these multiple examples.
