### ISSUE TITLE
Enhance VerifyRunningConfigLines Test Case for multiple matches

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/anta#1134]
When checking configurations, there are configuration lines that are not unique within the running-configuration.  

Below is an example configuration for OSPF and all `ip ospf` commands are standard to all OSPF interfaces:
```
interface Ethernet4/1/1.2000
  description "To switch port Eth 49/1.2000"
  mtu 9214
  encapsulation dot1q vlan 2000
  ip address 161.3.5.1/30
  ipv6 enable
  ipv6 address 2001::161:3:5:1/126
  ip ospf network point-to-point
  ip ospf authentication message-digest
  ip ospf area 0.0.0.0
!
```

If we check a configuration for `ip ospf area 0.0.0.0`, it's impossible to ensure interface Ethernet4/1/1.2000 has OSPF enabled.  

In order to do this we need one of 2 options:
1. Be able to match multiple lines of config. 
In this scenrio my match would be:
```
anta.tests.configuration:
  - VerifyRunningConfigLines:
      regex_patterns:
        - |
interface Ethernet4/1/1.2000
  description "To switch port Eth 49/1.2000"
  mtu 9214
  encapsulation dot1q vlan 2000
  ip address 161.3.5.1/30
  ipv6 enable
  ipv6 address 2001::161:3:5:1/126
  ip ospf network point-to-point
  ip ospf authentication message-digest
  ip ospf area 0.0.0.0
```
The problem with scenario is we only want to validate a single line, but we need to input 10 lines.

2. Provide what stanza the interesting line is in.  
```
anta.tests.configuration:
  - VerifyRunningConfigLines:
      interesting_stanza: interface Ethernet4/1/1.2000
      regex_patterns:
        - ip ospf area 0.0.0.0
 ```

**Comment by carl-baillargeon** [comment]
New test called `VerifyRunningConfig`.

Examples:
```
anta.tests.configuration:
  - VerifyRunningConfig:
      rules:

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        # TOP-LEVEL COMMANDS (no stanza)
        # When stanza is omitted, entries are checked against
        # top-level commands in the running config.
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

        # mode: exact + absent: false
        # The command must exist exactly as written.
        - stanza: null                               # null or omitted = top-level commands
          description: AAA authorization             # label shown in test results
          entries:
            - match: "aaa authorization exec default local"  # exact string to find
              mode: exact                            # exact | contains | regex (default: exact)
              absent: false                          # false = must be present (default: false)
              threshold: null                        # no numeric check (default: null)
              context: null                          # no custom failure message (default: null)

        # mode: exact + absent: true
        # This exact command must NOT exist in the config.
        - stanza: null
          description: No static enable password
          entries:
            - match: "enable password"
              mode: exact
              absent: true                           # true = must NOT be found
              threshold: null
              context: "Enable password must not be set in plaintext"

        # mode: contains + absent: false
        # At least one command must contain this substring.
        - stanza: null
          description: NTP servers configured
          entries:
            - match: "ntp server"
              mode: contains                         # any command containing "ntp server" is a match
              absent: false
              threshold: null
              context: null

        # mode: contains + absent: true
        # No command may contain this substring.
        - stanza: null
          description: No SNMP community strings
          entries:
            - match: "snmp-server community"
              mode: contains
              absent: true
              threshold: null
              context: "SNMP community strings are prohibited - use SNMPv3"

        # mode: regex + absent: false
        # At least one command must match this regex.
        - stanza: null
          description: Remote syslog configured
          entries:
            - match: "logging host \\S+"
              mode: regex                            # Python regex, matched via re.search
              absent: false
              threshold: null
              context: "At least one remote syslog server must be configured"

        # mode: regex + absent: true
        # No command may match this regex.
        - stanza: null
          description: No plaintext secrets
          entries:
            - match: "username .* secret 0 "
              mode: regex
              absent: true                           # no command may match this pattern
              threshold: null
              context: "Plaintext secrets (type 0) are prohibited"

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        # SINGLE STANZA
        # Target a specific config stanza by name.
        # Each element in the stanza list is a regex pattern
        # matched with re.match (anchored at start, NOT at end).
        # Use $ to anchor the end when needed, e.g.,
        # "interface Ethernet1$" to avoid matching Ethernet11.
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

        # Exact stanza with multiple entry checks
        - stanza: ["management api http-commands"]   # list with one element = one level deep
          description: Management API security
          entries:
            - match: "no shutdown"
              mode: exact
              absent: false
              threshold: null
              context: null
            - match: "protocol http"
              mode: contains
              absent: true                           # HTTP must not be configured
              threshold: null
              context: "Plaintext HTTP must be disabled on the management API"

        # Exact stanza with $ anchor to match only Ethernet1
        - stanza: ["interface Ethernet1$"]
          description: Uplink config
          entries:
            - match: "no switchport"
              mode: exact
              absent: false
              threshold: null
              context: "Ethernet1 must be a routed port"
            - match: "description"
              mode: contains
              absent: false
              threshold: null
              context: "Ethernet1 must have a description"

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        # THRESHOLD CHECKS
        # Compare a numeric value from the config against a
        # bound. Requires mode: regex with a capture group.
        # The first capture group is extracted and compared.
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

        # threshold.operator: ge (greater or equal)
        - stanza: ["interface Ethernet1$"]
          description: Uplink MTU
          entries:
            - match: "mtu (\\d+)"                    # capture group extracts the MTU value
              mode: regex                            # threshold requires regex mode
              absent: false
              threshold:
                value: 1500                          # expected bound
                operator: ge                         # ge = extracted value must be >= 1500
              context: "Uplink MTU must be at least 1500"

        # threshold.operator: eq (equal — the default)
        - stanza: ["router bgp \\d+"]
          description: BGP graceful-restart timer
          entries:
            - match: "graceful-restart restart-time (\\d+)"
              mode: regex
              absent: false
              threshold:
                value: 300                           # must be exactly 300
                operator: eq                         # eq = extracted value must == 300 (default)
              context: null

        # threshold.operator: le (less or equal)
        - stanza: ["management api http-commands"]
          description: eAPI session timeout
          entries:
            - match: "session timeout (\\d+)"
              mode: regex
              absent: false
              threshold:
                value: 5                             # must be at most 5 minutes
                operator: le                         # le = extracted value must be <= 5
              context: "eAPI session timeout must not exceed 5 minutes"

        # threshold.operator: ge on BGP max-paths
        - stanza: ["router bgp \\d+"]
          description: BGP ECMP paths
          entries:
            - match: "maximum-paths (\\d+)"
              mode: regex
              absent: false
              threshold:
                value: 4
                operator: ge
              context: "BGP must have at least 4 ECMP paths"

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        # NESTED STANZAS
        # Navigate multiple levels into the config tree.
        # Each element in the list matches one nesting level.
        # The path is exact: 2 elements = exactly 2 levels deep.
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

        # Two levels deep: management api > vrf
        - stanza: ["management api http-commands", "vrf MGMT"]
          description: eAPI enabled in MGMT VRF
          entries:
            - match: "no shutdown"
              mode: exact
              absent: false
              threshold: null
              context: null

        # Two levels deep: BGP > VRF
        - stanza: ["router bgp \\d+", "vrf DEV"]
          description: BGP VRF DEV router-id
          entries:
            - match: "router-id"
              mode: contains
              absent: false
              threshold: null
              context: "BGP VRF DEV must have a router-id"

        # Two levels deep: BGP > address-family
        - stanza: ["router bgp \\d+", "address-family evpn"]
          description: EVPN overlay peers
          entries:
            - match: "neighbor EVPN-OVERLAY-PEERS activate"
              mode: exact
              absent: false
              threshold: null
              context: null

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        # WILDCARD STANZAS
        # Use regex patterns to match multiple stanzas.
        # Each matched stanza is validated independently and
        # produces its own atomic result.
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

        # Wildcard at one level — any BGP ASN
        # Matches: "router bgp 65120", "router bgp 65001", etc.
        - stanza: ["router bgp \\d+"]
          description: BGP router-id
          entries:
            - match: "router-id \\d+\\.\\d+\\.\\d+\\.\\d+"
              mode: regex
              absent: false
              threshold: null
              context: "Every BGP instance must have a router-id"

        # Wildcard — all Ethernet interfaces
        # Produces one atomic result per matched interface.
        - stanza: ["interface Ethernet.*"]
          description: Interface descriptions
          entries:
            - match: "description"
              mode: contains
              absent: false
              threshold: null
              context: "Every Ethernet interface must have a description"

        # Wildcard + nested — all BGP VRFs must have a router-id
        - stanza: ["router bgp \\d+", "vrf .*"]
          description: BGP VRF router-ids
          entries:
            - match: "router-id"
              mode: contains
              absent: false
              threshold: null
              context: null

        # Wildcard + nested — all BGP VLANs must redistribute learned
        - stanza: ["router bgp \\d+", "vlan \\d+"]
          description: BGP VLAN learned routes
          entries:
            - match: "redistribute learned"
              mode: exact
              absent: false
              threshold: null
              context: null

        # Wildcard with threshold — fleet-wide MTU check
        - stanza: ["interface Ethernet\\d+$"]
          description: Global MTU policy
          entries:
            - match: "mtu (\\d+)"
              mode: regex
              absent: false
              threshold:
                value: 1500
                operator: ge
              context: "All Ethernet interfaces must have MTU >= 1500"

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        # STANZA EXISTENCE CHECK
        # To verify a stanza exists, target it and check for any
        # command inside. If the stanza is missing, the test fails
        # with: "No stanza matching '<pattern>' found in running-config"
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

        - stanza: ["router bgp \\d+"]
          description: BGP must be configured
          entries:
            - match: "router-id"
              mode: contains
              absent: false
              threshold: null
              context: "BGP is not configured on this device"

```

For stanza, we should try an exact dict lookup first and fall back to regex if no exact match is found.
