### ISSUE TITLE
Add a warning when duplicate test exists in the catalog

### ISSUE THREAD

**Issue by mtache** [aristanetworks/anta#825]
Currently, we allow the user to define duplicate tests in the catalog without any warning.
If the user defines 10 identical tests (same test name and same inputs), there should only be one result (because we manipulate sets of AntaTestDefinition that removes duplicates).
This issue is a reminder to add a warning when duplicates are found.

**Comment by kosichd** [comment]
@mtache I think I am running into something similar to this, as my intention is to have anta.tests.interfaces used with several blocks of interfaces and a tag, then another block of interfaces and a tag, and so on. 

When I do so, it seems to ignore the first tag (eor1g_non_fabric), meaning when I run the NRFU command with --tags eor1g_non_fabric, it doesn't execute the test. It does work when I run the command with --tags osw

anta.tests.interfaces:
  - VerifyInterfacesStatus:
      interfaces:
        - name: Ethernet51
          status: up
        - name: Ethernet52
          status: up
        - name: Ethernet53
          status: up
        - name: Ethernet54
          status: up
      filters:
        **tags: ['eor1g_non_fabric']**
      interfaces:
        - name: Ethernet51
          status: up
      filters:
        **tags: ['osw']**

**Comment by mtache** [comment]
Hi @kosichd
Your use case is different from what is described in this issue: same test AND same inputs.

What you want to achieve is supported using the following catalog:
```
anta.tests.interfaces:
- VerifyInterfacesStatus:
   filters:
     tags: ['eor1g_non_fabric']
   interfaces:
     - name: Ethernet51
        status: up
     - name: Ethernet52
        status: up
     - name: Ethernet53
        status: up
     - name: Ethernet54
        status: up
- VerifyInterfacesStatus:
   filters:
     tags: ['osw']
   interfaces:
     - name: Ethernet51
        status: up
```
