### ISSUE TITLE
bug: Test case erroneously run when more than one tag in inventory 

### ISSUE THREAD

**Issue by kosichd** [aristanetworks/anta#974]
When using tags with the anta.tests.interfaces/VerifyInterfacesStatus test, there seems to be an issue where tests are being executed that should not be. 

This seems to happen when a switch has more than one tag in the inventory file.

 In the below example catalog and inventory files, "management_switch" has two tags, 'osw' and 'DUB'

When running the NRFU command with --tags osw, it should only execute InterfaceStatus against interfaces E51 and E52. However, it seems to be running it against E53/E54 also, which is actually part of the 'DUB' tag, not 'osw'

This causes the test case to fail - 

![ANTA_RUN](https://github.com/user-attachments/assets/ad682697-1cb5-4b04-89c3-b2d7c67c4441)

Steps to recreate:
1) Use the below to create inventory and catalog files
2) From the CLI, run:

```
anta nrfu --username USERNAME--password PASSWORD --inventory recreate_inventory.yml  --catalog recreate_catalog.yml  --tags osw
```

## inventory file 

```
anta_inventory:  
  hosts:
  - host: x.x.x.x
    name: "switch1"
    tags: ['DUB']
  - host :  x.x.x.x
    name: "management_switch"
    tags: ['osw', 'DUB']
```

## catalog file

```
anta.tests.interfaces:
- VerifyInterfacesStatus:
   filters:
     tags: ['DUB', 'GRN']
   interfaces:
     - name: Ethernet51
       status: up
     - name: Ethernet52
       status: up
     - name: Ethernet53
       status: up
     - name: Ethernet54
       status: up
- VerifyInterfacesStatus:
   filters:
     tags: ['osw']
   interfaces:
     - name: Ethernet51
       status: up
     - name: Ethernet52
       status: up
```
